import { ILanguage } from '@/ts/language'
import { ILocale, ITheme } from '@/ts/store'

export const SETTINGS = {
    RADARR_URL: 'radarr_url',
    SONARR_URL: 'sonarr_url',
    SOURCE_LANGUAGES: 'source_languages',
    TARGET_LANGUAGES: 'target_languages',
    SONARR_SETTINGS_COMPLETED: 'sonarr_settings_completed',
    RADARR_SETTINGS_COMPLETED: 'radarr_settings_completed',
    SERVICE_TYPE: 'service_type',
    LIBRETRANSLATE_URL: 'libretranslate_url',
    SHOW_SCHEDULE: 'show_schedule',
    MOVIE_SCHEDULE: 'movie_schedule',
    MAX_TRANSLATIONS_PER_RUN: 'max_translations_per_run',
    AUTOMATION_ENABLED: 'automation_enabled',
    LIBRARY_DISK_SCAN_ENABLED: 'library_disk_scan_enabled',
    SUBTITLE_NAMING_ENABLED: 'subtitle_naming_enabled',
    SUBTITLE_EXTRACT_ENABLED: 'subtitle_extract_enabled',
    SUBTITLE_MAINTENANCE_SCHEDULE: 'subtitle_maintenance_schedule',
    SUBTITLE_EXTRACT_MAX_PER_RUN: 'subtitle_extract_max_per_run',
    TRANSLATION_SCHEDULE: 'translation_schedule',
    OPENAI_MODEL: 'openai_model',
    ANTHROPIC_MODEL: 'anthropic_model',
    ANTHROPIC_VERSION: 'anthropic_version',
    LOCAL_AI_ENDPOINT: 'local_ai_endpoint',
    LOCAL_AI_MODEL: 'local_ai_model',
    GEMINI_MODEL: 'gemini_model',
    DEEPSEEK_MODEL: 'deepseek_model',
    OPENROUTER_MODEL: 'openrouter_model',
    OPENROUTER_ENDPOINT: 'openrouter_endpoint',
    OPENROUTER_TEMPERATURE: 'openrouter_temperature',
    OPENROUTER_MAX_TOKENS: 'openrouter_max_tokens',
    ZAI_MODEL: 'zai_model',
    ZAI_ENDPOINT: 'zai_endpoint',
    OPENCODE_GO_MODEL: 'opencode_go_model',
    OPENCODE_GO_ENDPOINT: 'opencode_go_endpoint',
    QWEN_MODEL: 'qwen_model',
    QWEN_MT_MODEL: 'qwen_mt_model',
    QWEN_ENDPOINT: 'qwen_endpoint',
    XAI_MODEL: 'xai_model',
    XAI_OAUTH_MODEL: 'xai_oauth_model',
    XAI_ENDPOINT: 'xai_endpoint',
    MISTRAL_MODEL: 'mistral_model',
    MISTRAL_ENDPOINT: 'mistral_endpoint',
    XAI_OAUTH_CONNECTION: 'xai_oauth_connection',
    AI_PROMPT: 'ai_prompt',
    THEME: 'theme',
    LOCALE: 'locale',
    MOVIE_AGE_THRESHOLD: 'movie_age_threshold',
    SHOW_AGE_THRESHOLD: 'show_age_threshold',
    FIX_OVERLAPPING_SUBTITLES: 'fix_overlapping_subtitles',
    STRIP_SUBTITLE_FORMATTING: 'strip_subtitle_formatting',
    PRESERVE_LINE_BREAKS: 'preserve_line_breaks',
    ADD_TRANSLATOR_INFO: 'add_translator_info',
    CUSTOM_AI_PARAMETERS: 'custom_ai_parameters',
    SUBTITLE_VALIDATION_ENABLED: 'subtitle_validation_enabled',
    SUBTITLE_VALIDATION_MAXDURATIONSECS: 'subtitle_validation_maxdurationsecs',
    SUBTITLE_VALIDATION_MINDURATIONMS: 'subtitle_validation_mindurationms',
    SUBTITLE_VALIDATION_MINSUBTITLELENGTH: 'subtitle_validation_minsubtitlelength',
    SUBTITLE_VALIDATION_MAXSUBTITLELENGTH: 'subtitle_validation_maxsubtitlelength',
    SUBTITLE_VALIDATION_MAXFILESIZEBYTES: 'subtitle_validation_maxfilesizebytes',
    AI_CONTEXT_PROMPT_ENABLED: 'ai_context_prompt_enabled',
    AI_CONTEXT_PROMPT: 'ai_context_prompt',
    AI_CONTEXT_BEFORE: 'ai_context_before',
    AI_CONTEXT_AFTER: 'ai_context_after',
    ACTIVE_SYSTEM_PROMPT_PROFILE_ID: 'active_system_prompt_profile_id',
    ACTIVE_CONTEXT_PROMPT_PROFILE_ID: 'active_context_prompt_profile_id',
    USE_BATCH_TRANSLATION: 'use_batch_translation',
    MAX_BATCH_SIZE: 'max_batch_size',
    CACHE_CANCELLED_PROGRESS: 'cache_cancelled_progress',
    CACHE_CANCELLED_QUALITY_THRESHOLD: 'cache_cancelled_quality_threshold',
    JEV_SKIP_NON_DIALOGUE: 'jev_skip_non_dialogue',
    JEV_REJECT_UNTRANSLATED: 'jev_reject_untranslated',
    USE_SUBTITLE_TAGGING: 'use_subtitle_tagging',
    REMOVE_LANGUAGE_TAG: 'remove_language_tag',
    SUBTITLE_TAG: 'subtitle_tag',
    IGNORE_CAPTIONS: 'ignore_captions',
    REQUEST_TIMEOUT: 'request_timeout',
    LIBRETRANSLATE_REQUEST_TIMEOUT: 'libretranslate_request_timeout',
    GOOGLE_REQUEST_TIMEOUT: 'google_request_timeout',
    BING_REQUEST_TIMEOUT: 'bing_request_timeout',
    MICROSOFT_REQUEST_TIMEOUT: 'microsoft_request_timeout',
    YANDEX_REQUEST_TIMEOUT: 'yandex_request_timeout',
    DEEPL_REQUEST_TIMEOUT: 'deepl_request_timeout',
    OPENAI_REQUEST_TIMEOUT: 'openai_request_timeout',
    ANTHROPIC_REQUEST_TIMEOUT: 'anthropic_request_timeout',
    LOCALAI_REQUEST_TIMEOUT: 'localai_request_timeout',
    GEMINI_REQUEST_TIMEOUT: 'gemini_request_timeout',
    DEEPSEEK_REQUEST_TIMEOUT: 'deepseek_request_timeout',
    OPENROUTER_REQUEST_TIMEOUT: 'openrouter_request_timeout',
    ZAI_REQUEST_TIMEOUT: 'zai_request_timeout',
    OPENCODE_GO_REQUEST_TIMEOUT: 'opencode_go_request_timeout',
    QWEN_REQUEST_TIMEOUT: 'qwen_request_timeout',
    QWEN_MT_REQUEST_TIMEOUT: 'qwen_mt_request_timeout',
    XAI_REQUEST_TIMEOUT: 'xai_request_timeout',
    XAI_OAUTH_REQUEST_TIMEOUT: 'xai_oauth_request_timeout',
    MISTRAL_REQUEST_TIMEOUT: 'mistral_request_timeout',
    MAX_RETRIES: 'max_retries',
    RETRY_DELAY: 'retry_delay',
    RETRY_DELAY_MULTIPLIER: 'retry_delay_multiplier',
    AUTH_ENABLED: 'auth_enabled',
    ONBOARDING_COMPLETED: 'onboarding_completed',
    NAVIGATE_TO_DETAILS_ON_REQUEST: 'navigate_to_details_on_request',
    OPENAI_REQUEST_TEMPLATE: 'openai_request_template',
    ANTHROPIC_REQUEST_TEMPLATE: 'anthropic_request_template',
    LOCAL_AI_CHAT_REQUEST_TEMPLATE: 'local_ai_chat_request_template',
    LOCAL_AI_GENERATE_REQUEST_TEMPLATE: 'local_ai_generate_request_template',
    DEEPSEEK_REQUEST_TEMPLATE: 'deepseek_request_template',
    QWEN_REQUEST_TEMPLATE: 'qwen_request_template',
    XAI_REQUEST_TEMPLATE: 'xai_request_template',
    MISTRAL_REQUEST_TEMPLATE: 'mistral_request_template',
    GEMINI_REQUEST_TEMPLATE: 'gemini_request_template',
    LANGUAGE_CODE_FORMAT: 'language_code_format',
    RADARR_DEFAULT_INCLUDE: 'radarr_default_include',
    SONARR_DEFAULT_INCLUDE: 'sonarr_default_include',
    DASHBOARD_ACTIVITY_WINDOW_HOURS: 'dashboard_activity_window_hours',
    DASHBOARD_PRIMARY_LANGUAGE: 'dashboard_primary_language',
    PLEX_SET_SELECTED_SUBTITLE: 'plex_set_selected_subtitle',
    PLEX_DEFAULT_SUBTITLE_LANGUAGE: 'plex_default_subtitle_language',
    PLEX_TRANSLATE_ON_LIBRARY_NEW: 'plex_translate_on_library_new',
    PLEX_TRANSLATE_MOVIES_ON_LIBRARY_NEW: 'plex_translate_movies_on_library_new',
    PLEX_TRANSLATE_EPISODES_ON_LIBRARY_NEW: 'plex_translate_episodes_on_library_new'
} as const

export interface ISettings {
    radarr_url: string
    sonarr_url: string
    service_type: string
    libretranslate_url: string
    show_schedule: string
    movie_schedule: string
    max_translations_per_run: string
    translation_schedule: string
    source_languages: string | ILanguage[]
    target_languages: string | ILanguage[]
    automation_enabled: string
    library_disk_scan_enabled: string
    subtitle_naming_enabled: string
    subtitle_extract_enabled: string
    subtitle_maintenance_schedule: string
    subtitle_extract_max_per_run: string
    sonarr_settings_completed: string
    radarr_settings_completed: string
    openai_model: string
    anthropic_model: string
    anthropic_version: string
    local_ai_endpoint: string
    local_ai_model: string
    gemini_model: string
    deepseek_model: string
    openrouter_model: string
    openrouter_endpoint: string
    openrouter_temperature: string
    openrouter_max_tokens: string
    zai_model: string
    zai_endpoint: string
    opencode_go_model: string
    opencode_go_endpoint: string
    qwen_model: string
    qwen_mt_model: string
    qwen_endpoint: string
    xai_model: string
    xai_oauth_model: string
    xai_endpoint: string
    mistral_model: string
    mistral_endpoint: string
    xai_oauth_connection: string
    ai_prompt: string
    movie_age_threshold: string
    show_age_threshold: string
    fix_overlapping_subtitles: string
    strip_subtitle_formatting: string
    preserve_line_breaks: string
    add_translator_info: string
    theme: ITheme
    locale: ILocale
    subtitle_validation_enabled: string
    subtitle_validation_maxfilesizebytes: string
    subtitle_validation_minsubtitlelength: string
    subtitle_validation_maxsubtitlelength: string
    subtitle_validation_mindurationms: string
    subtitle_validation_maxdurationsecs: string
    ai_context_prompt_enabled: string
    ai_context_prompt: string
    ai_context_before: string
    ai_context_after: string
    active_system_prompt_profile_id: string
    active_context_prompt_profile_id: string
    use_batch_translation: string
    max_batch_size: string
    cache_cancelled_progress: string
    cache_cancelled_quality_threshold: string
    jev_skip_non_dialogue: string
    jev_reject_untranslated: string
    use_subtitle_tagging: string
    remove_language_tag: string
    subtitle_tag: string
    ignore_captions: string
    request_timeout: string
    libretranslate_request_timeout: string
    google_request_timeout: string
    bing_request_timeout: string
    microsoft_request_timeout: string
    yandex_request_timeout: string
    deepl_request_timeout: string
    openai_request_timeout: string
    anthropic_request_timeout: string
    localai_request_timeout: string
    gemini_request_timeout: string
    deepseek_request_timeout: string
    openrouter_request_timeout: string
    zai_request_timeout: string
    opencode_go_request_timeout: string
    qwen_request_timeout: string
    qwen_mt_request_timeout: string
    xai_request_timeout: string
    xai_oauth_request_timeout: string
    mistral_request_timeout: string
    max_retries: string
    retry_delay: string
    retry_delay_multiplier: string
    auth_enabled: string
    onboarding_completed: string
    navigate_to_details_on_request: string
    openai_request_template: string
    anthropic_request_template: string
    local_ai_chat_request_template: string
    local_ai_generate_request_template: string
    deepseek_request_template: string
    qwen_request_template: string
    xai_request_template: string
    mistral_request_template: string
    gemini_request_template: string
    language_code_format: string
    radarr_default_include: string
    sonarr_default_include: string
    dashboard_activity_window_hours: string
    dashboard_primary_language: string
    plex_set_selected_subtitle: string
    plex_default_subtitle_language: string
    plex_translate_on_library_new: string
    plex_translate_movies_on_library_new: string
    plex_translate_episodes_on_library_new: string
}

export const ENCRYPTED_SETTINGS = {
    API_KEY: 'api_key',
    RADARR_API_KEY: 'radarr_api_key',
    SONARR_API_KEY: 'sonarr_api_key',
    OPENAI_API_KEY: 'openai_api_key',
    ANTHROPIC_API_KEY: 'anthropic_api_key',
    GEMINI_API_KEY: 'gemini_api_key',
    DEEPSEEK_API_KEY: 'deepseek_api_key',
    OPENROUTER_API_KEY: 'openrouter_api_key',
    ZAI_API_KEY: 'zai_api_key',
    OPENCODE_GO_API_KEY: 'opencode_go_api_key',
    QWEN_API_KEY: 'qwen_api_key',
    XAI_API_KEY: 'xai_api_key',
    MISTRAL_API_KEY: 'mistral_api_key',
    DEEPL_API_KEY: 'deepl_api_key',
    LIBRETRANSLATE_API_KEY: 'libretranslate_api_key',
    LOCAL_AI_API_KEY: 'local_ai_api_key',
    TYPESAFE_API_KEY: 'typesafe_api_key'
} as const

export interface IEncryptedSettings {
    api_key: string
    radarr_api_key: string
    sonarr_api_key: string
    openai_api_key: string
    anthropic_api_key: string
    gemini_api_key: string
    deepseek_api_key: string
    openrouter_api_key: string
    zai_api_key: string
    opencode_go_api_key: string
    qwen_api_key: string
    xai_api_key: string
    mistral_api_key: string
    deepl_api_key: string
    libretranslate_api_key: string
    local_ai_api_key: string
    typesafe_api_key: string
}

export const SERVICE_TYPE = {
    LIBRETRANSLATE: 'libretranslate',
    OPENAI: 'openai',
    ANTHROPIC: 'anthropic',
    LOCALAI: 'localai',
    DEEPL: 'deepl',
    GEMINI: 'gemini',
    DEEPSEEK: 'deepseek',
    OPENROUTER: 'openrouter',
    ZAI: 'zai',
    OPENCODE_GO: 'opencode-go',
    QWEN: 'qwen',
    QWEN_MT: 'qwen-mt',
    XAI: 'xai',
    XAI_OAUTH: 'xai-oauth',
    MISTRAL: 'mistral',
    GOOGLE: 'google',
    BING: 'bing',
    MICROSOFT: 'microsoft',
    YANDEX: 'yandex'
} as const

export type ServiceType = (typeof SERVICE_TYPE)[keyof typeof SERVICE_TYPE]

export interface IFilterOptions {
    logLevel: string
}

export interface ILogEntry {
    logLevel: string
    message: string
    formattedTime: string
    formattedDate: string
    formattedSource: string
    category: string
    stackTrace?: string
}
